apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  volumes:
  - name: task-pv-volume
    persistentVolumeClaim: 
      claimName: task-pv-claim
  containers:
  - name: ubuntu
    image: galinakaz/ubuntu_for_kube_project:1.0 
    volumeMounts:
        - mountPath: "/external"
          name: task-pv-volume
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
